// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primestream.proto

package primestreampb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NumberRequest struct {
	Request              int64    `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberRequest) Reset()         { *m = NumberRequest{} }
func (m *NumberRequest) String() string { return proto.CompactTextString(m) }
func (*NumberRequest) ProtoMessage()    {}
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_primestream_e66dcd28b3796dfe, []int{0}
}
func (m *NumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberRequest.Unmarshal(m, b)
}
func (m *NumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberRequest.Marshal(b, m, deterministic)
}
func (dst *NumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberRequest.Merge(dst, src)
}
func (m *NumberRequest) XXX_Size() int {
	return xxx_messageInfo_NumberRequest.Size(m)
}
func (m *NumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NumberRequest proto.InternalMessageInfo

func (m *NumberRequest) GetRequest() int64 {
	if m != nil {
		return m.Request
	}
	return 0
}

type NumbermanyResponse struct {
	Response             int64    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumbermanyResponse) Reset()         { *m = NumbermanyResponse{} }
func (m *NumbermanyResponse) String() string { return proto.CompactTextString(m) }
func (*NumbermanyResponse) ProtoMessage()    {}
func (*NumbermanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_primestream_e66dcd28b3796dfe, []int{1}
}
func (m *NumbermanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumbermanyResponse.Unmarshal(m, b)
}
func (m *NumbermanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumbermanyResponse.Marshal(b, m, deterministic)
}
func (dst *NumbermanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumbermanyResponse.Merge(dst, src)
}
func (m *NumbermanyResponse) XXX_Size() int {
	return xxx_messageInfo_NumbermanyResponse.Size(m)
}
func (m *NumbermanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NumbermanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NumbermanyResponse proto.InternalMessageInfo

func (m *NumbermanyResponse) GetResponse() int64 {
	if m != nil {
		return m.Response
	}
	return 0
}

func init() {
	proto.RegisterType((*NumberRequest)(nil), "primestream.NumberRequest")
	proto.RegisterType((*NumbermanyResponse)(nil), "primestream.NumbermanyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NumberServiceClient is the client API for NumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NumberServiceClient interface {
	Primestream(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (NumberService_PrimestreamClient, error)
}

type numberServiceClient struct {
	cc *grpc.ClientConn
}

func NewNumberServiceClient(cc *grpc.ClientConn) NumberServiceClient {
	return &numberServiceClient{cc}
}

func (c *numberServiceClient) Primestream(ctx context.Context, in *NumberRequest, opts ...grpc.CallOption) (NumberService_PrimestreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NumberService_serviceDesc.Streams[0], "/primestream.NumberService/Primestream", opts...)
	if err != nil {
		return nil, err
	}
	x := &numberServicePrimestreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NumberService_PrimestreamClient interface {
	Recv() (*NumbermanyResponse, error)
	grpc.ClientStream
}

type numberServicePrimestreamClient struct {
	grpc.ClientStream
}

func (x *numberServicePrimestreamClient) Recv() (*NumbermanyResponse, error) {
	m := new(NumbermanyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NumberServiceServer is the server API for NumberService service.
type NumberServiceServer interface {
	Primestream(*NumberRequest, NumberService_PrimestreamServer) error
}

func RegisterNumberServiceServer(s *grpc.Server, srv NumberServiceServer) {
	s.RegisterService(&_NumberService_serviceDesc, srv)
}

func _NumberService_Primestream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NumberServiceServer).Primestream(m, &numberServicePrimestreamServer{stream})
}

type NumberService_PrimestreamServer interface {
	Send(*NumbermanyResponse) error
	grpc.ServerStream
}

type numberServicePrimestreamServer struct {
	grpc.ServerStream
}

func (x *numberServicePrimestreamServer) Send(m *NumbermanyResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NumberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primestream.NumberService",
	HandlerType: (*NumberServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Primestream",
			Handler:       _NumberService_Primestream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primestream.proto",
}

func init() { proto.RegisterFile("primestream.proto", fileDescriptor_primestream_e66dcd28b3796dfe) }

var fileDescriptor_primestream_e66dcd28b3796dfe = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0xcc,
	0x4d, 0x2d, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0xd2, 0xe4, 0xe2, 0xf5, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x82, 0x30, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x60, 0x5c, 0x25, 0x03, 0x2e, 0x21, 0x88, 0xd2, 0xdc, 0xc4, 0xbc, 0xca, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x29, 0x2e, 0x8e, 0x22, 0x28, 0x1b, 0xaa, 0x01, 0xce, 0x37, 0x8a,
	0x85, 0x19, 0x1e, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc3, 0xc5, 0x1d, 0x80, 0xb0,
	0x5c, 0x48, 0x4a, 0x0f, 0xd9, 0x75, 0x28, 0xee, 0x90, 0x92, 0xc7, 0x22, 0x87, 0x6c, 0xb1, 0x01,
	0xa3, 0x13, 0x7f, 0x14, 0x2f, 0x92, 0x9a, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x07, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x38, 0x91, 0x76, 0x3e, 0xf5, 0x00, 0x00, 0x00,
}
